// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LeG1dRYiZoh8PhtcINR-mClcMuos8ss',
    appId: '1:458313168139:web:958de802ad2471d5f85e0e',
    messagingSenderId: '458313168139',
    projectId: 'gwaap-d429a',
    authDomain: 'gwaap-d429a.firebaseapp.com',
    storageBucket: 'gwaap-d429a.firebasestorage.app',
    measurementId: 'G-99E5GFZVW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7Jb42mL2nyacot4pfpUkOU2vXFJ7nJM',
    appId: '1:458313168139:android:9ed4a4063d81ab02f85e0e',
    messagingSenderId: '458313168139',
    projectId: 'gwaap-d429a',
    storageBucket: 'gwaap-d429a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtNFBQ3PCXr1lCNZbZsK-zoAzvWNLeC3c',
    appId: '1:458313168139:ios:dae7d81f4b5f8fe0f85e0e',
    messagingSenderId: '458313168139',
    projectId: 'gwaap-d429a',
    storageBucket: 'gwaap-d429a.firebasestorage.app',
    iosBundleId: 'com.example.gwaupp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtNFBQ3PCXr1lCNZbZsK-zoAzvWNLeC3c',
    appId: '1:458313168139:ios:dae7d81f4b5f8fe0f85e0e',
    messagingSenderId: '458313168139',
    projectId: 'gwaap-d429a',
    storageBucket: 'gwaap-d429a.firebasestorage.app',
    iosBundleId: 'com.example.gwaupp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1LeG1dRYiZoh8PhtcINR-mClcMuos8ss',
    appId: '1:458313168139:web:4411b2d3ad509e5bf85e0e',
    messagingSenderId: '458313168139',
    projectId: 'gwaap-d429a',
    authDomain: 'gwaap-d429a.firebaseapp.com',
    storageBucket: 'gwaap-d429a.firebasestorage.app',
    measurementId: 'G-NP5NE8RT2D',
  );
}
